package moe.shizuku.manager.screenshots

import android.content.res.Configuration
import androidx.compose.ui.tooling.preview.Preview

/**
 * Locale previews rendered on the phone device spec in the light configuration.
 *
 * [name] stays the plain fastlane metadata directory so `copy_screenshots.sh` can read the locale
 * straight out of the rendered file name.
 *
 * No `showSystemUi`: the screenshot renderer ignores it. PorterScaffold insets through
 * WindowInsets.safeDrawing, which layoutlib reports as zero, so content simply starts at the top
 * edge with no overlap artefact.
 *
 * Generated by `fastlane/generate_screenshots.sh`; the checked-in state is en-US only.
 */
@Preview(
    locale = "en",
    name = "en-US",
    device = DS_PHONE,
    uiMode = Configuration.UI_MODE_NIGHT_NO or Configuration.UI_MODE_TYPE_NORMAL,
)
annotation class PlayStoreLocales

/**
 * The same, in the dark configuration. See [PlayStoreLocales].
 *
 * The `uiMode` is not cosmetic. PorterTheme(dark = true) selects the Material colour scheme only;
 * ServiceStatusCard tints the status icon through colorResource(R.color.porter_status_running),
 * which resolves against the render configuration. Without UI_MODE_NIGHT_YES a dark shot paints
 * values/porter_status.xml's light-surface green on a dark card, a combination the app never
 * produces because ShizukuApplication flips the resource configuration and the theme together
 * through AppCompatDelegate.setDefaultNightMode.
 */
@Preview(
    locale = "en",
    name = "en-US",
    device = DS_PHONE,
    uiMode = Configuration.UI_MODE_NIGHT_YES or Configuration.UI_MODE_TYPE_NORMAL,
)
annotation class PlayStoreLocalesDark
