plugins {
    id "com.android.application"
    id "dev.rikka.tools.refine"
}

android {
    namespace = "eu.darken.porter.shell"
    defaultConfig {
        versionCode = rootProject.ext.versionCode
        versionName = rootProject.ext.versionName
        buildConfigField "String", "MANAGER_APPLICATION_ID", "\"${project(':manager').android.defaultConfig.applicationId}\""
    }
    buildTypes {
        debug {
            multiDexEnabled = false
        }
        release {
            minifyEnabled = true
            proguardFiles = ["proguard-rules.pro"]
        }
    }
    dependenciesInfo {
        includeInApk = false
    }
    lint {
        checkReleaseBuilds = false
    }
    buildFeatures {
        buildConfig = true
    }
}

android.applicationVariants.all { variant ->
    variant.outputs.all {
        def outDir = new File(rootDir, "out")
        def mappingPath = new File(outDir, "mapping").absolutePath
        variant.assembleProvider.get().doLast {
            if (variant.getBuildType().isMinifyEnabled()) {
                copy {
                    from variant.mappingFileProvider.get()
                    into mappingPath
                    rename { String fileName ->
                        mappingPath + File.separator + "cmd-v${variant.versionName}.txt"
                    }
                }
            }
        }
    }
}

androidComponents.onVariants(androidComponents.selector().all()) { variant ->
    configurations.create("porshDex${variant.name.capitalize()}") {
        canBeConsumed = true
        canBeResolved = false
        outgoing.artifact(variant.artifacts.get(com.android.build.api.artifact.SingleArtifact.APK.INSTANCE))
    }
}

dependencies {
    implementation libs.hidden.compat
    compileOnly libs.hidden.stub
}
