plugins {
    id "idea"
    id "com.android.library" apply false
    id "org.jetbrains.kotlin.android" apply false
}

idea.module {
    excludeDirs += file("out")
}

subprojects { subproject ->
    plugins.withId("com.android.base") {
        android {
            compileSdk = 37
            buildToolsVersion = "37.0.0"
            ndkVersion = "29.0.13113456"
            defaultConfig {
                minSdk = 24
                targetSdk = 37
            }
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_21
                targetCompatibility = JavaVersion.VERSION_21
            }
        }
    }
}

def versioning = new Properties()
file("version.properties").withInputStream { versioning.load(it) }
def major = versioning["project.versioning.major"] as int
def minor = versioning["project.versioning.minor"] as int
def patch = versioning["project.versioning.patch"] as int
def build = versioning["project.versioning.build"] as int
ext {
    versionCode = major * 10000000 + minor * 100000 + patch * 1000 + build * 10
    versionName = "${major}.${minor}.${patch}-${versioning["project.versioning.type"]}${build}"
}
