plugins {
    id "com.android.application"
}

android {
    namespace = "eu.darken.porter.compat"
    defaultConfig {
        applicationId = "moe.shizuku.privileged.api"
        versionCode = rootProject.ext.versionCode
        versionName = rootProject.ext.versionName
    }
    signingConfigs {
        sign {}
    }
    buildTypes {
        debug { signingConfig = signingConfigs.sign }
        release { signingConfig = signingConfigs.sign }
    }
    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "porter-compat-v${variant.versionName}-${variant.name}.apk"
        }
    }
}

apply from: rootProject.file("signing.gradle")

androidComponents.onVariants(androidComponents.selector().all()) { variant ->
    configurations.create("embedded${variant.name.capitalize()}") {
        canBeConsumed = true
        canBeResolved = false
        outgoing.artifact(variant.artifacts.get(com.android.build.api.artifact.SingleArtifact.APK.INSTANCE))
    }
}
