#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR"/porsh.dex

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX, please check the tutorial in Porter app"
  exit 1
fi

if [ $(getprop ro.build.version.sdk) -ge 34 ]; then
  if [ -w $DEX ]; then
    echo "On Android 14+, app_process cannot load writable dex."
    echo "Attempting to remove the write permission..."
    chmod 400 $DEX
    if [ -w $DEX ]; then
      echo "Cannot remove the write permission of $DEX."
      echo "You can copy to file to terminal app's private directory (/data/data/<package>, so that remove write permission is possible"
      exit 1
    else
      echo "Write permission was removed successfully."
    fi
  fi
fi

# Replace PKG below with your terminal app's application id. Porter's own id is filled in when the app exports this file.
[ -z "$PORSH_APPLICATION_ID" ] && export PORSH_APPLICATION_ID="PKG" && export MANAGER_APPLICATION_ID="MANAGER_PKG"
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=porsh eu.darken.porter.shell.PorterShellLoader "$@"
